### ISSUE TITLE
支持iPhone X系列

### ISSUE THREAD

**Issue by VillageMud** [lsmakethebest/LSNavigationController#5]
![image](https://user-images.githubusercontent.com/12798195/50063276-a393f780-01e6-11e9-9a2b-f62f4dfd3910.png)

**Comment by VillageMud** [comment]
![image](https://user-images.githubusercontent.com/12798195/50063310-d211d280-01e6-11e9-98d0-63112d954dbf.png)

**Comment by VillageMud** [comment]
老铁，更新下，已经处理好了

**Comment by lsmakethebest** [comment]
已更新，欢迎pull request
